name: 'stock_market_analytics'
version: '1.0'
config-version: 2

profile: 'stock_market_profile'

model-paths: ["models"]

models:
  stock_market_analytics:

    staging:
      +schema: STAGING
      +materialized: view

    marts:
      +schema: MARTS
      +materialized: table